version: "3.8"

services:
  app:
    build: .
    container_name: yd
    ports:
      - "8003:8000"
    volumes:
      - ./downloads:/app/downloads
      - ./static:/app/static
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: yd_redis
    restart: always